/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controllador.Select;
import Controllador.actualizar;
import Controllador.aniadir;
import Controllador.eliminar;
import Entidades.PokemonDeUsuario;
import Entidades.los3Ints;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Propietario
 */
public class evolucionesDe1Pokemon extends javax.swing.JFrame {

    /**
     * Creates new form evolucionesDe1Pokemon
     */
    private int id_de_pokemon;
    private detallePokemon vistaAnterior;
    private String nombre;
    public evolucionesDe1Pokemon(int id, detallePokemon vista, String nombrePokemon) throws SQLException {
        initComponents();
        
        this.nombre= nombrePokemon;
        this.id_de_pokemon=id;
        this.vistaAnterior=vista;
        llenaLista();
        llenarTabla(false);
        jLabNombrePokemon.setText(nombrePokemon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextIDPARAQUITAR = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabNombrePokemon = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIDPARACAMBIAR = new javax.swing.JTextField();
        jTextNIVELPARACAMBIARNUEVO = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonAniadir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTextIAniadirivel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre evolucion", "Nivel requerido"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Quitar este pokemon");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Posibles evoluciones del pokemon");

        jLabNombrePokemon.setText(" ");

        jButton3.setText("Cambiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("ID de pokemon que se quiere cambiar su nivel para evolucionar");

        jLabel4.setText("Nuevo nivel requerido");

        jLabel5.setText("ID de evolucion");

        jButtonAniadir.setText("Añadir");
        jButtonAniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAniadirActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jLabel6.setText("Seleciones los pokemons \ny elija 1 nivel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabNombrePokemon)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextIDPARAQUITAR, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextIAniadirivel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonAniadir, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)))))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldIDPARACAMBIAR, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTextNIVELPARACAMBIARNUEVO))
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addComponent(jLabNombrePokemon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextIDPARAQUITAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldIDPARACAMBIAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextNIVELPARACAMBIARNUEVO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextIAniadirivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButtonAniadir)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int idAQuitar = Integer.parseInt(jTextIDPARAQUITAR.getText());
        eliminar e = new eliminar();
        int id_pokemon= 0;
        try {
            id_pokemon = obtener_id_exacto_de_pokemon();
            e.EliminarEvolucionAPokemon(id_pokemon, idAQuitar);
            llenarTabla(true);
        } catch (SQLException ex) {
            Logger.getLogger(evolucionesDe1Pokemon.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        //CAMBIAR
        
        int nro = Integer.parseInt(jTextNIVELPARACAMBIARNUEVO.getText());
        int idEvolucion = Integer.parseInt(jTextFieldIDPARACAMBIAR.getText());
        try {
            int id_pokOriginal = obtener_id_exacto_de_pokemon();
            actualizar a = new actualizar();
            a.ActualizarEvolucionAPokemon(id_pokOriginal, idEvolucion, nro);
        } catch (SQLException ex) {
            Logger.getLogger(evolucionesDe1Pokemon.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            llenarTabla(true);
        } catch (SQLException ex) {
            Logger.getLogger(evolucionesDe1Pokemon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void llenaLista() throws SQLException{
        Select s = new Select();
        ResultSet res = s.todosLosPokemones();
        DefaultListModel model = new DefaultListModel();
        while(res.next()){
            model.addElement(new String(res.getString(2)));
        }
        s.cerrarConsulta();
        jList1.setModel(model);
        jList1.setSelectedIndex(0);
    }
    
    private void jButtonAniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAniadirActionPerformed
        // TODO add your handling code here:
        int nro = Integer.parseInt(jTextIAniadirivel.getText());
        aniadir an = new aniadir();
        int[] seleccionados = jList1.getSelectedIndices();
        int exacto;
        try {
            exacto = obtener_id_exacto_de_pokemon();
            for(int a: seleccionados){
                 an.AniadirEvolucionAPokemon(exacto, a, nro);
                 llenarTabla(true);
             }
              try {
               llenarTabla(true);
              } catch (SQLException ex) {
                    Logger.getLogger(detallePokemon.class.getName()).log(Level.SEVERE, null, ex);
                }
        } catch (SQLException ex) {
            Logger.getLogger(evolucionesDe1Pokemon.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //AÑADIR NUEVO POKEMON COMO EVOLUCION
    }//GEN-LAST:event_jButtonAniadirActionPerformed

    private int obtener_id_exacto_de_pokemon() throws SQLException{
        Select s = new Select();
        System.out.println("NOMBRE DE POKEMON_X_USER: "+nombre);
        ResultSet res = s.obtenerTodasLasEvolucionesDe1PokemonXNombre(nombre);
        int i=0;
        while(res.next()){
             i = res.getInt(1);
             System.out.println("RESULTAOD: "+String.valueOf(i));
            s.cerrarConsulta();
            return i;
        }
        s.cerrarConsulta();
        return 0;
    }
    
    public void activar(int id_pok_de_user, detallePokemon vista, String nombre) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(evolucionesDe1Pokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(evolucionesDe1Pokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(evolucionesDe1Pokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(evolucionesDe1Pokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new evolucionesDe1Pokemon(id_pok_de_user, vista, nombre).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(evolucionesDe1Pokemon.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    private void llenarLista() throws SQLException{
        Select s = new Select();
        ResultSet res = s.todosLosPokemones();
        ArrayList<String> lista = new ArrayList<String>();
        while(res.next()){
            lista.add(res.getString(2));
        }
        DefaultListModel model = new DefaultListModel();
        Object[] row = new Object[2];
        for(String a: lista){
            model.addElement(a);
        }
        jList1.setModel(model);
    }
    
    private void llenarTabla(boolean recarga) throws SQLException{
        
        int asd = obtener_id_exacto_de_pokemon();
        System.out.println("DATOS de pokemon: "+ String.valueOf(asd));
        Select s = new Select();
        ResultSet res = s.obtenerTodasLasEvolucionesDe1Pokemon(asd);
         ArrayList<los3Ints> lista = new ArrayList<los3Ints>();
        while(res.next()){
            lista.add(new los3Ints(res.getInt(1), res.getString(2), res.getInt(3)));
            System.out.println("DATOS ID: "+ String.valueOf(res.getInt(1))+", NOMBRE: "
                    + ""+res.getString(2)+", NIVEL: "+String.valueOf(res.getInt(3)));
        }
        DefaultTableModel model;
        if(recarga){
            model = new javax.swing.table.DefaultTableModel(
                                            new Object [][] {},  
                        new String [] {"ID", "Nombre evolucion", "Nivel requerido"});
            
        } else {
            model =  (DefaultTableModel)jTable1.getModel();
        }
        Object[] row = new Object[3];
        for(los3Ints a: lista){
            row[0]=a.getId1();
            row[1]=a.getNombre();
            row[2]=a.getNivel();
            System.out.println("ID: "+ a.getId1()+", NOMBRE: "+a.getNombre()+", NIVEL: "+a.getNivel());
            model.addRow(row);
        }
        if(recarga){
           jTable1.setModel(model);
        }
        s.cerrarConsulta();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAniadir;
    private javax.swing.JLabel jLabNombrePokemon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldIDPARACAMBIAR;
    private javax.swing.JTextField jTextIAniadirivel;
    private javax.swing.JTextField jTextIDPARAQUITAR;
    private javax.swing.JTextField jTextNIVELPARACAMBIARNUEVO;
    // End of variables declaration//GEN-END:variables
}
